ORG 0000H
SETB P0.2 ;SET OUTPUT PIN
SETB P0.0 ;SET INPUT PIN
SETB P0.1 ;SET INPUT PIN
LOOP: CLR C
ORL C,/P0.0  ;OR OPERATION IN PO.O WITH CARRY BIT
ANL C,/P0.1  ;AND OPERATION IN P0.2 IN CARRY BIT
CPL C  ; COMPLEMENTING THE CARRY BIT
MOV P0.2,C  ;COPYING THE 2 PORT TO C BIT
SJMP LOOP   ;JMP TO LOOP STATEMENT
END
